# image will be published to ghcr.io/<user>/<name>
name: aurora-custom-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ignic/akmods/repo/fedora-%OS_VERSION%/ignic-akmods-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ignic/keyd/repo/fedora-%OS_VERSION%/ignic-keyd-fedora-%OS_VERSION%.repo
    install:
      - xmm7360-pci
      - keyd
      - kitty
      - snapper
      - btrfs-assistant

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.bitwarden.desktop
        - org.videolan.VLC
        - org.gnome.meld
        - sh.cider.Cider
        - com.usebottles.bottles
        - com.todoist.Todoist
        - io.podman_desktop.PodmanDesktop
        - com.calibre_ebook.calibre
        - org.localsend.localsend_app
        - org.gimp.GIMP
        - com.ktechpit.whatsie
        - org.telegram.desktop

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
